In [2]:
import numpy as np

In [6]:
#Print even number 1 20 ina an array
a=np.array([x for x in range(2,21,2)])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
#print number 1 to 10 in even number in first line and 1 to 9 odd in second
b=np.array([[x for x in range(2,11,2)],[y for y in range(1,10,2)]])
b

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [20]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [25]:
np.linspace(0.0,1.0,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
np.arange(1,10001).reshape(4,2500)

array([[    1,     2,     3, ...,  2498,  2499,  2500],
       [ 2501,  2502,  2503, ...,  4998,  4999,  5000],
       [ 5001,  5002,  5003, ...,  7498,  7499,  7500],
       [ 7501,  7502,  7503, ...,  9998,  9999, 10000]])

In [35]:
#Use numpy tocreate an array of 20 even integer from 2 to 40 integer then reshape  into 4 by 5 array
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [43]:
import random
%timeit rolls_list=[random.randrange(1,7) for i in range(6000000)]

7 s ± 46.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [46]:
%timeit rolls_array=[np.random.randint(1,7,6000000)]

247 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
